SELECT
    "A1"."EMPLOYEE_ID"    "EMPLOYEE_ID",
    "A1"."FIRST_NAME"     "FIRST_NAME",
    "A1"."LAST_NAME"      "LAST_NAME",
    "A1"."EMAIL"          "EMAIL",
    "A1"."PHONE_NUMBER"   "PHONE_NUMBER",
    "A1"."HIRE_DATE"      "HIRE_DATE",
    "A1"."JOB_ID"         "JOB_ID",
    "A1"."SALARY"         "SALARY",
    "A1"."COMMISSION_PCT" "COMMISSION_PCT",
    "A1"."MANAGER_ID"     "MANAGER_ID",
    "A1"."DEPARTMENT_ID"  "DEPARTMENT_ID"
FROM
    "HR"."EMPLOYEES" "A1";