-- CRIANDO GRUPOS UTILIZANDO A CLÁUSULA GROUP BY
-- SEQUÊNCIA LÓGICA:
-- 1 - WHERE    -> SELECIONAR AS LINHA A SEREM RECUPERADAS
-- 2 - GROUP BY -> FORMAR OS GRUPOS
--

SELECT DEPARTMENT_ID "ID DEPARTAMENTO", ROUND(AVG(SALARY),2) "MÉDIA SALARIAL"
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

-- REGRA: TODAS AS COLUNAS OU EXPRESSÕES NA LISTA DA CLÁUSULA SELECT
--        QUE NÃO ESTÃO EM UMA FUNÇÃO DE GRUPO DEVEM ESTAR NA CLÁUSULA GROUP BY
SELECT DEPARTMENT_ID, JOB_ID,  SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID, JOB_ID;

-- CONSULTAS INCORRETAS UTILIZANDO FUNÇÕES DE GRUPO
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES;
-- =>
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

-- O WHERE SELECIONA LINHAS PARA COMPOR O GRUPO QUE SERÁ CRIADO
-- ASSIM O WHERE NÃO PODE CONTER FUNÇÕES DE GRUPO
-- ** ALTERNATIVA HAVING
SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
WHERE MAX(SALARY) > 10000
GROUP BY DEPARTMENT_ID;

-- CORRIGINDO 
-- RESTRIGINDO GRUPOS UTILIZANDO A CLÁUSULA HAVING

SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) > 10000;

SELECT JOB_ID, SUM(SALARY) TOTAL
FROM EMPLOYEES
WHERE JOB_ID <> 'SA_REP'
GROUP BY JOB_ID
HAVING SUM(SALARY) > 10000
ORDER BY SUM(SALARY);

-- AINHANDO FUNÇÕES DE GRUPO
SELECT MAX(AVG(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;
