--
-- SEÇÃO 10 - AULA 13
-- AGREGANDO DADOS UTILIZANDO FUNÇÕES DE GRUPO
--

-- UTILIZANDO AS FUNÇÕES AVG E SUM

SELECT AVG(SALARY), SUM(SALARY), TO_CHAR(SUM(SALARY), 'FML99G999G999D00')
FROM EMPLOYEES;


-- UTILIZANDO AS FUNÇÕES MIN E MAX
SELECT MIN(HIRE_DATE), MAX(HIRE_DATE)
FROM EMPLOYEES;

SELECT TO_CHAR(MIN(SALARY), 'FML99G999G999D0') "MENOR SALÁRIO", 
       TO_CHAR(MAX(SALARY), 'FML99G999G999D00') "MAIOR SALÁRIO"
FROM EMPLOYEES;


-- UTILIZANDO FUNÇÃO COUNT

SELECT COUNT(*) 
FROM EMPLOYEES;

SELECT COUNT(COMMISSION_PCT), COUNT(*) 
FROM EMPLOYEES;

SELECT COUNT(NVL(COMMISSION_PCT,0)) 
FROM EMPLOYEES;


-- UTILIZANDO AS FUNÇÕES MIN E MAX

SELECT COUNT(DISTINCT(DEPARTMENT_ID)) QTD_DEPTOS, COUNT(DEPARTMENT_ID)
FROM EMPLOYEES;


-- FUNÇÕES DE GRUPO E VALORES NULOS
-- **** FUNÇÕES DE GRUPO IGNORAM VALORES NULOS

SELECT AVG(COMMISSION_PCT) -- IGNORA OS FUNCIONARIOS COM COMMISSION_PCT É NULO -> ERRADO
FROM EMPLOYEES;
-- CORRETO ABAIXO
SELECT AVG(NVL(COMMISSION_PCT, 0)) 
FROM EMPLOYEES;

SELECT AVG(COMMISSION_PCT), AVG(NVL(COMMISSION_PCT, 0)) 
FROM EMPLOYEES;